# Generated by Django 4.0.5 on 2022-06-21 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_create_time_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 21, 15, 0, 47, 9484)),
        ),
    ]
